name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  LOCATION_ORIGIN: https://etozhkirill.ru
  YM_COUNTER_ID: ${{ secrets.YM_COUNTER_ID }}

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Run lint and tests
        run: npm run lint && npm run test

      - name: Build
        run: npm run build

  deploy:
    needs: test_and_build
    runs-on: ubuntu-latest
    steps:
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ETOZHKIRILL_BLOG }}'
          channelId: live
          projectId: etozhkirill-blog
